<a href="https://colab.research.google.com/github/joynaomi81/Python-Programming/blob/main/Numpy_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* NumPy is a Python library.
* NumPy stands for Numerical Python.


In [1]:
import numpy as np

1-D Arrays

In [4]:
a = numpy.array([1, 2, 3, 4, 5])

print(a)

[1 2 3 4 5]


2-D Arrays

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


3-D arrays

In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Access Array Elements

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr[0])

1


In [12]:
print(arr[2] + arr[3]) # Access the third and fourth elements from the array and add them.

7


NumPy Array Slicing


In [13]:
arr = np.array([112, 200, 354, 476, 590, 699, 717])

print(arr[1:5])

[200 354 476 590]


In [14]:
print(arr[4:]) # Slice elements from index 4 to the end of the array

[590 699 717]


NumPy Data Types

In [15]:
a = np.array([1, 2, 3, 4, 7])

print(a.dtype)

int64


In [18]:
a = np.array(['car', 'bus', 'truck'])

print(a.dtype)

<U5


<U5 refers to a Unicode string type in NumPy with a maximum length of 5 characters.

Shape of an Array

In [19]:
print(a.shape)

(3,)


In [20]:
print(a.size)

3


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
arr = np.array(['apple', 'banana', 'cherry', 'watermelon', 'orange', 'mango'])

print(arr.dtype)

newarr = arr.reshape(2, 3)

print(newarr)

<U10
[['apple' 'banana' 'cherry']
 ['watermelon' 'orange' 'mango']]


Iterating Arrays

In [25]:
arr = np.array([[1.4, 2.5, 3.4], [4.5, 5.5, 6.7]])

for x in arr:
  print(x)

[1.4 2.5 3.4]
[4.5 5.5 6.7]


In [26]:
arr = np. array([['apple', 'banana', 'cherry'], ['watermelon', 'orange', 'mango']])

for x in arr:
  print(x)

['apple' 'banana' 'cherry']
['watermelon' 'orange' 'mango']


Joining NumPy Arrays

In [30]:
arr = np. array([['apple', 'banana', 'cherry'], ['watermelon', 'orange', 'mango']])

arr2 = np.array([[1,2,3], [5,6,7]])

arr3 = np.concatenate((arr, arr2))

print(arr3)

[['apple' 'banana' 'cherry']
 ['watermelon' 'orange' 'mango']
 ['1' '2' '3']
 ['5' '6' '7']]


Splitting NumPy Arrays

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8 ,9 ,10])

newarr = np.array_split(arr, 3)

print(newarr)


[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


Line Spacing

In [33]:
arr = np.linspace(1, 5, 20)

print(arr)

[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


* Min
* Max
* Sum

In [34]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(a.min())
print(a.max())
print(a.sum())



1
10
55


Sorting Arrays

In [36]:
arr = np.array([1, 2, 4, 3, 6, 5])
print(np.sort(arr))

[1 2 3 4 5 6]


In [38]:
arr = np.array(['banana', 'cherry', 'apple', 'mango'])

print(np.sort(arr))

['apple' 'banana' 'cherry' 'mango']
